language: node_js
node_js:
  - 10
after_success:
  - nyc report --reporter=text-lcov | coveralls
before_deploy:
  - npm install netlify-cli -g
  - npm run production
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -p -d ./dist
  skip_cleanup: true
  on:
    branch: master